version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "80:80"

  flask-backend:
    build: 
      context: ./flask-backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"