version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        TARGET_STAGE: production
        REACT_APP_API_URL: anirec-load-balancer-1590555672.eu-central-1.elb.amazonaws.com/
    ports:
      - "80:80"

  flask-backend:
    build: 
      context: ./flask-backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
