FROM python:3.9.12
ENV FLASK_DEBUG=True
ENV FLASK_APP=app:create_app()

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install pytest

COPY . .

EXPOSE 8080

CMD ["flask", "run", "--host=0.0.0.0", "--port=8080"]